### ISSUE TITLE
No Completions

### ISSUE THREAD

**Issue by esetnik** [petervanderdoes/git-flow-completion#7]
I can't seem to get any completions if I use the latest `homebrew` git instead of default git provided with El Capitan.

To reproduce:
1. Using zsh and homebrew `brew install git`
2. ==> Pouring git-2.8.1.el_capitan.bottle.tar.gz
3. edit `~/.zshrc` add plugins=(git) and `source ~/.git-flow-completion.zsh`
4. try `git flow TAB` and the completion is a list of files in the directory not the flow command options.
5. `brew remove git && git --version`
git version 2.6.4 (Apple Git-63)
6. `git flow TAB` and the completion is the list of git flow options:
```
 git flow
bugfix   -- Manage your bugfix branches.
config   -- Manage your configuration.
delete   -- Delete the branch you are currently on.
feature  -- Manage your feature branches.
finish   -- Finish the branch you are currently on.
hotfix   -- Manage your hotfix branches.
init     -- Initialize a new git repo with support for the branching model.
publish  -- Publish the branch you are currently on.
rebase   -- Rebase the branch you are currently on.
release  -- Manage your release branches.
support  -- Manage your support branches.
version  -- Shows version information.
```

**Comment by wyllyan** [comment]
It may help you: https://github.com/robbyrussell/oh-my-zsh/issues/1717#issuecomment-22540099

**Comment by codeHatcher** [comment]
that referenced issue ended up helping me
